### ISSUE TITLE
Removing child node lets siblings disappear

### ISSUE THREAD

**Issue by maltmann-muc** [mbraak/jqTree#582] opened 2019-11-04 08:06 UTC
I have nodes and child nodes (one level).
When calling removeNode($childnode), the siblings disappear.

Debugged (jqTree 1.4.11 on Chrome) and found this issue:
- JqTreeWidget.prototype.removeNode() calls node.remove()
- Node.prototype.remove() sets this.parent to null
- Back in JqTreeWidget.prototype.removeNode(),  this._refreshElements(node.parent) is then called with node.parent as null

**Comment by mbraak** [comment] 2019-11-04 11:15
I couldn't reproduce this. I used this code:

```js
var n = $tree.tree("getNodeByName", "Spinosauroids");
console.log(n);
$tree.tree("removeNode", n);
```

**Comment by mbraak** [comment] 2019-11-04 11:16
I updated the code so it correctly calls `_refreshElements` with a valid parent. This is fixed in #583.

However, I could not reproduce the error.

**Closed** 2019-11-18 17:36 UTC
