### ISSUE TITLE
Icon for initial opened root nodes not display as opened

### ISSUE THREAD

**Issue by ivan-kolesov** [mbraak/jqTree#839] opened 2024-10-10 14:06 UTC
Could you help me with display tree with initial data?
jqTree 1.8.5

```
<div id="tree1" data-url="/nodes/"></div>
<script>
    $(function() {
        const initData = [
            {
                name: "Saurischia",
                id: 1,
                children: [
                    { name: "Herrerasaurians", id: 2 },
                    {
                        name: "Theropods",
                        id: 3,
                        load_on_demand: true,
                    },
                    {
                        name: "Sauropodomorphs",
                        id: 16,
                        load_on_demand: true,
                    },
                ],
            },
            {
                name: "Ornithischians",
                id: 23,
                load_on_demand: true,
            },
        ];

        $('#tree1').tree({
            data: initData
        });
});
```
Render as showed, root nodes have closed icon style:

<img width="491" alt="image" src="https://github.com/user-attachments/assets/df4f9d35-3725-47b8-8d59-ac1a5d07fc11">

But when I expand a child node with loading on demand then those root nodes become open icon style.

**Comment by mbraak** [comment] 2024-10-10 17:05
I'll have a look.

**Comment by mbraak** [comment] 2024-10-11 08:23
I couldn't reproduce the error. When I try this the icons are correct.

![Scherm­afbeelding 2024-10-11 om 10 23 15](https://github.com/user-attachments/assets/939590cf-d974-4378-a2af-4d330042aeec)

**Comment by ivan-kolesov** [comment] 2024-10-11 08:27
Will try to make it in a sandbox

**Comment by mbraak** [comment] 2024-10-15 15:25
Thanks. I will have a look.

**Comment by mbraak** [comment] 2024-10-15 15:34
The 'Saurischia' node is closed but the children are displayed. That's because the `jqtree.css` file is not included. I think that might fix the issue.

````
https://mbraak.github.io/jqTree/jqtree.css
````

**Comment by ivan-kolesov** [comment] 2024-10-15 15:44
Just updated the sandbox. Now 'Saurischia' is closed but how to make it opened? I want to init a tree on demand with some branch open in specific depth.

**Comment by mbraak** [comment] 2024-10-15 16:32
You can use the `autoOpen` option.

* `autoOpen: 0` to open the first level
* Also see https://mbraak.github.io/jqTree/#options-autoopen

**Comment by ivan-kolesov** [comment] 2024-10-15 17:47
> You can use the `autoOpen` option.

`autoOpen` tryes to open all nested children - it's not that I need for. I have a huge tree which loads on demand and want to open all parent to a specific child. Show on the picture (node `Ceratosaurians`).
![2024-10-15 at 19 44](https://github.com/user-attachments/assets/64259115-1c8c-4223-8e28-85410304c2b3)

**Comment by mbraak** [comment] 2024-10-16 05:57
A possible solution:

* Ensure that the selected node is in the initial data.
* Select the node after the tree data is loaded:

```
const $tree = $("#tree1");

// Wait until the initial data is loaded
$tree.on("tree.init", function (e) {
    const node = $tree.tree("getNodeById", 11);
    if (node) {
        // Selecting the node will open its parents
        $tree.tree("selectNode", node);
    }
});

$tree.tree({
    data: ExampleData.exampleData,
});
```

* The difficulty is that the node must be in the initial data.
* Alternative for `selectNode` is to open its parent:
  ```
  const parent = $tree.tree('getNodeById', 8);
  $tree.tree('openNode', parent);
  ```
* It might also be possible to load the data on demand and then open it, but that's not supported by jqtree. Maybe it's possible to write custom code. Note that calling `openNode` will load the children of the node on demand.

**Comment by ivan-kolesov** [comment] 2024-10-16 08:39
Hi. Thank you, the first helps me. Update the sandbox: https://codepen.io/ivan-kolesov/pen/GRVWPyo

**Comment by mbraak** [comment] 2024-10-17 05:58
Closing the issue.

**Closed by mbraak** 2024-10-17 05:58 UTC
