### ISSUE TITLE
onDragStop not working.

### ISSUE THREAD

**Issue by techybirds** [mbraak/jqTree#565] opened 2019-04-17 11:43 UTC
var $tree = $('#tree1').tree({
						singleBranchExpand: false,
                                                data: data,
                                                dragAndDrop: true,
                                                autoOpen: false,
                                                onDragStop : function(node, $li){
                                                	alert(" asdasd asd ");
                                                }
                                          });

Not alerting asdasd asd after drag stopped.

**Comment by mbraak** [comment] 2019-04-17 18:14
I will look into it

**Comment by mbraak** [comment] 2019-04-18 08:21
I could not reproduce this error. I tested it on Chrome.

NB: `onDragStop` is called when you release the mouse button; so when a node is actually moved

**Comment by mbraak** [comment] 2019-05-22 12:49
No progress here. Closing.

**Closed by mbraak** 2019-05-22 12:49 UTC
