### ISSUE TITLE
Possible to prevent `updateNode` from setting focus to updated treeitem?

### ISSUE THREAD

**Issue by evaneykelen** [mbraak/jqTree#624] opened 2020-10-07 09:22 UTC
It seems `updateNode` is setting focus to the updated treeitem (`jqtree-title jqtree_common`). In my case this is undesirable since it removes the focus from a form the user is filling out.

Step by step:

1. User clicks inside a form textfield to edit a tree node title.

2. User tabs to / clicks inside the next textfield. 

3. The title textfield loses focus which triggers a server call that calls `updateNode` out-of-band (server saves field, which triggers websocket call, which calls client-side code, which calls `updateNode`).

(so far so good)

4. I can see that the next textfield briefly gets focus and then loses it again since `updateNode` overrides the focus and sets it to the updated treeitem (I can see this by inspecting `document.activeElement` in several places).

5. The user must refocus the next field which is a subpar user experience.

Things I've tried:

* Looking for the equivalent to `mustSetFocus: false` for `updateNode`. Doesn't seem to be available.

* Storing current focus and then restoring it after calling `updateNode`. This is causing issues since my form saves its data on blur causing race conditions if I start calling focus().

**Comment by mbraak** [comment] 2020-10-07 14:31
I will have a look

**Comment by mbraak** [comment] 2020-10-07 14:52
I can reproduce this issue. After `updateNode` the currently selected node is reselected; and it also sets the focus. I will see if it's possible to skip setting the focus in this case.

**Comment by mbraak** [comment] 2020-10-08 07:58
This is fixed in pr #625. When calling `updateNode` the focus is now only set if the tree originally had the focus.
The pr will be merged shortly.

**Comment by evaneykelen** [comment] 2020-10-08 08:25
Wow @mbraak that's wonderful!

**Comment by evaneykelen** [comment] 2020-10-08 15:10
[update] Did some initial testing with 1.5.1: issue solved! Will put it through more testing.

**Closed** 2020-10-09 09:51 UTC

**Comment by mbraak** [comment] 2020-10-09 09:52
The issue is closed automatically because the pr was merge. Feel free to reopen it if there's still an issue.
