### ISSUE TITLE
Node with child and without child are not aligned

### ISSUE THREAD

**Issue by mihirpatel83** [mbraak/jqTree#568] opened 2019-05-31 15:20 UTC
How to align all node in same level as it seems nodes with child and without not showing properly due to the collapseable icon.
![View Product](https://user-images.githubusercontent.com/592418/58715920-db0def00-8395-11e9-945d-db80a592dc84.png)

The last two nodes should be aligned with above nodes as they are at same level. Can you please guide on how to resolve it? Below is my jqtree code

`$(treeId).tree({
                    data: $.parseJSON(data),
                    autoOpen: false,
                    openedIcon: " ",
                    closedIcon: " ",
                    onCreateLi: function (node, $li) {
                        const $item = $li.find(".jqtree-title");
                        const nodeId = node.id;
                        var chkd = false;                      
                        var itemCheckbox = $('<input />')
                                .attr({type: 'checkbox',
                                    id: 'ecat_' + node.id,
                                    value: node.id,
                                    checked: chkd
                                });
                        $item.before(itemCheckbox);
                    }
                });`

**Comment by mbraak** [comment] 2019-06-01 11:33
I tried your example code, but I could not reproduce the error. I got the following result:

<img width="141" alt="Screenshot 2019-06-01 at 13 30 56" src="https://user-images.githubusercontent.com/235558/58747892-93f52c00-8471-11e9-9726-e493abd33b85.png">

**Comment by mihirpatel83** [comment] 2019-06-03 13:36
The problem is still there when there are nodes with child and nodes without child. In above example you can see that test12344 and 7 should be below Bedroom because these all are at same level but as the "+" sign is added it doesnt display all nodes in straight line. I have used below Css to add "+"

`ul.jqtree-tree .jqtree-folder .jqtree-toggler.jqtree-closed:before {        
        font-family: 'feather' !important;
        content: "\e99d";
    }
    ul.jqtree-tree .jqtree-folder .jqtree-toggler:before {        
        font-family: 'feather' !important;
        content: "\e982";        
    }`

**Comment by mihirpatel83** [comment] 2019-06-03 14:58
Please see this image again. Nodes with no child has margin applied so that it aligns with other nodes. But as soon as I add checkbox i need that margin to be applied to checkbox and not the <span> tag displaying text.
![View Product(1)](https://user-images.githubusercontent.com/592418/58811821-80230480-85ee-11e9-9819-9024c5d04a55.png)

**Comment by mihirpatel83** [comment] 2019-06-03 15:05
Awesome... That's working for me as well. Thank you :)

**Comment by mbraak** [comment] 2019-06-03 17:48
I'm glad that it works. Closing the issue.

**Closed by mbraak** 2019-06-03 17:48 UTC
