### ISSUE TITLE
Autoscroll not working if tree is located lower on screen

### ISSUE THREAD

**Issue by themre** [mbraak/jqTree#467] opened 2017-01-09 06:32 UTC
Hi,
Autoscroll is not getting actual position of node when dragging if tree is located lower on the page. If for example you put margin-bottom: 1000px in this example (https://mbraak.github.io/jqTree/examples/07_autoscroll/) and scroll down and try to move node, it will scroll to bottom instantly. That's because it gets offset from top of page instead getting actual X,Y on screen. Any easy solution for this?

**Comment by mbraak** [comment] 2017-01-09 07:44
I will try to replicate this error.

**Comment by mbraak** [comment] 2017-01-09 08:31
I have put a `margin-bottom: 1000px` on the `h1` element in the autoscroll example. But I cannot reproduce this error using Chrome.
Which browser are you using?

**Comment by themre** [comment] 2017-01-09 08:38
Chrome also. I've created a demo gif.
![jqtree_scroll_demo](https://cloud.githubusercontent.com/assets/10845050/21760834/6656b58e-d64f-11e6-8552-dfc71e443200.gif)

**Comment by mbraak** [comment] 2017-01-09 09:24
I still cannot reproduce this on OSX. Which OS are you running?

**Comment by themre** [comment] 2017-01-09 10:03
Oh, wait, I know what the problem is... If I later change the position of wrapper div after the jqTree was initialized, then it breaks. So add this code after intialization of jqTree:
`$("h1").css({'margin-top':'1000px'})`

**Comment by mbraak** [comment] 2017-01-09 10:08
Thanks! Now I can reproduce the problem.

**Comment by mbraak** [comment] 2017-01-09 11:11
I haved added a solution to the `issue-467` branch. It seems to fix the problem on my computer. Could you please check if it works for you?

**Comment by themre** [comment] 2017-01-09 11:43
I haven't build it, I just removed those lines in built version and it works! So I guess this is the correct solution, thanks!

**Comment by mbraak** [comment] 2017-01-09 11:46
This is now merged in the `dev` branch.

**Closed by mbraak** 2017-01-09 11:46 UTC
