### ISSUE TITLE
Stopping drag and drop from external html areas.

### ISSUE THREAD

**Issue by WriterStat** [mbraak/jqTree#577] opened 2019-10-11 04:49 UTC
Hi Marco, Thanks again!

I just noticed that I can drag and drop external html areas that are on the same page into the jqTree areas. Like external menu items from the page, external icons on the page, almost any html object/tag found on the page.

At first, I thought way cool! But then it messes up the Tree. Is there a way to turn off dragging and dropping from all external areas into the tree area in general? While keeping the cut/copy and paste options? And keeping the drag and drop options that are already in the tree?

It's probably something we did here. Or something we didn't understand here. But if there is a global way in the tree. It sort of surprised us when I saw someone do it. =))

**Comment by mbraak** [comment] 2019-10-11 06:24
I tried to reproduce this, but I couldn't. Is it possible that this is caused by other js code?

**Comment by WriterStat** [comment] 2019-10-11 07:18
Hi Marco, 

Definitely could be, we use a bunch of Bootstrap and Bootstrap related js. I'll try and reproduce a test script using the jqtree demos and send along.

And I'll look up a way to stop the external dropping in the Tree1 div using some additional external js.

**Comment by WriterStat** [comment] 2020-05-04 07:05
Hi Marco, I'm pretty sure this is us because we have set the tree elements to be contenteditable. Wonder how we could limit drag and drop to only tree elements, but allow cut and paste of text from outside of tree. Anyhow I think this is beyond the scope of the jqtree.

**Comment by mbraak** [comment] 2020-05-04 16:34
Ok thanks. Closing the issue.

**Closed by mbraak** 2020-05-04 16:34 UTC
