### ISSUE TITLE
new some examples about setState function

### ISSUE THREAD

**Issue by habout632** [mbraak/jqTree#301] opened 2014-06-19 03:51 UTC
I want to set the state of some node ,but in documentation ,I can't find any example about setState function ,so can you add some intro about that ?

**Comment by jimiayler** [comment] 2015-08-20 15:19
Hi, Marco -- This seems to be the right place to ask my questions around ```getState``` and ```setState```. I'm not able to leverage its ```setState``` for saving dynamically created nodes and especially when a page refreshes. 

I am using forms to both save specific data about my web app, but also to leverage part of the results from that form to populate an instance of jqTree with new tree nodes and/or children. That's a very straightforward process, utilizing jqTree's native functions ```addNodeAfter``` and ```appendNode```. The issue is in getting and setting those states for when the form submits and the page resets accordingly.

There is a parameter for saving the last state of open/closed nested nodes, ```saveState: true```, that works well, but any nodes/children dynamically generated by the form during its lifecycle are destroyed when the form submits and the page refreshes. 

But the closest I get to an answer about this is this quote above:

    You can use the functions getState and setState to save the state of the tree.

    var state = $('#tree1').tree('getState');

    $('#tree1').tree('setState', state);

If I run ```getState``` on ```addNodeAfter``` I get a console.log() result like:

    {"open_nodes":[1],"selected_node":[4]}

With the same selected/created node scenario for ```setState```, I get in the console:

    {"type":"tree","timeStamp":1440016021305,"jQuery111307363375960849226":true,"isTrigger":3,"namespace":"refresh","namespace_re":{},"target":{"jQuery111307363375960849226":16}}

i.e. an almost completely different response without any direct relationship, as far as I can see, in their nomenclature.

And, if I try to submit my form and simultaneously save my new node data:

               ('form').on('submit', function(e){
                    var state = $tree.tree('getState');
                    var savedstate = $tree.tree('setState', state);

                    console.log(state);
                    console.log(savedstate);
                    //e.preventDefault();
                });
I neither get the data saved nor get any console example. Note the commented-out ```e.preventDefault();``` statement -- comment that back in and I do get those two, very different results in the console, but, of course, my form won't trigger and as far as I can see no data is saved.

So -- I guess I have two questions:

1.) What is the relationship between these two very different results from ```getState``` and ```setState``` in jqTree? And:

2.) How can I submit a form, save the newly created tree nodes and have them re-populate the tree when the page reloads?

Apologies for going on at length here -- thanks for any assistance you may be able to provide.

**Comment by mbraak** [comment] 2015-08-21 06:55
Hello Jim,

I see that the `getState` function returns some random thing( `{"type":"tree","timeStamp":...`). That is very confusing, I will change it so it returns the `jQuery` element.

Note that you cannot use `getState` and `setState` to rebuild a tree. These functions only handle data about the selected and open nodes.

If you want to get the tree data and build a new tree you can do the following:

You can get the tree data using the [toJson](https://mbraak.github.io/jqTree/#functions-tojson) function.

```js
var tree_json = $('#tree1').tree('toJson');
```
Then you can use this data to create a new tree. Let's say we have a `div` with id `tree2`:

```html
<div id="tree2"></div>
```
```js
$('#tree2').tree({
    data: JSON.parse(tree_json)
});
```

I hope that this answers your question.

Cheers,
Marco

**Comment by jimiayler** [comment] 2015-08-21 14:48
Yes, sir, that does it, with a little help form local storage. When the form is submitted, everything goes to local storage via toJson:

               $('form').on('submit', function(e){
                    var tree_json = $('#tree1').tree('toJson');
                    localStorage.setItem('treeData', tree_json);
                });
No need to stringify it, either, which is a happy surprise. When the page loads, it checks for any instance of ````treeData```` in local storage and builds out the tree from that -- if not, it does a fresh draw from a separate AJAX call:

                    if (localStorage.getItem("treeData") === null) {
                            $('#tree1').tree({
                            data: data,
                            autoOpen: true,
                            dragAndDrop: true,
                            saveState: true,
                            onCreateLi: function(node, $li) {
                                $li.attr('id', node.id);
                            }
                        });
                    } else {
                            var savedTree = JSON.parse(localStorage.getItem('treeData'));
                            $('#tree1').tree({
                                data: savedTree,
                                autoOpen: true,
                                dragAndDrop: true,
                                saveState: true,
                                onCreateLi: function(node, $li) {
                                    $li.attr('id', node.id);
                            }
                        });
                    }
And ````saveState: true```` maintains the state of open and closed nodes perfectly. Works like a charm -- thanks Marco!

**Comment by mbraak** [comment] 2015-08-21 14:53
Ok great! Closing the issue

**Closed by mbraak** 2015-08-21 14:53 UTC
