### ISSUE TITLE
autoscroll issue

### ISSUE THREAD

**Issue by hbaptiste** [mbraak/jqTree#402] opened 2015-09-29 20:35 UTC
For some reasons the autoscroll feature when I drag a node won't work on my project.
As I don't have any error message, I would like to ask you what can prevent it from working.
The dragged node is way out of its container but the scrollbar stays still.
Thanks for your help. And for jqTree.

**Comment by mbraak** [comment] 2015-09-30 07:07
Please have a look at the [autoscroll example](https://mbraak.github.io/jqTree/examples/07_autoscroll.html). Perhaps your code is different.

```html
<div id="scroll-container">
    <div id="tree1"></div>
</div>
```

The css:
```css
#scroll-container {
    height: 200px;
    overflow-y: scroll;
    position: relative;  /* ie7 fix */
    -ms-user-select: none;
    user-select: none;
}
```

**Comment by hbaptiste** [comment] 2015-09-30 07:44
Thanks for your help. Unfortunately for me, I have the same structure and the same css as your example.

**Comment by mbraak** [comment] 2015-09-30 08:36
Hmm that's strange. Perhaps some other css on your page is interfering?

**Comment by hbaptiste** [comment] 2015-09-30 09:34
After some tests, I think it appends when we render the tree in an element (documentFragment) and then appends that element to the dom. Is there a way to refresh the tree's dimension after it has been rendered?
Thanks again for your help.

**Comment by mbraak** [comment] 2015-09-30 09:45
It could be a problem if you change the parent of the tree.

Could you share some code? Then I can try to reproduce the bug.

**Comment by hbaptiste** [comment] 2015-09-30 10:22
Here is my code to reproduce the bug.
```
var treeviewWrapper = jQuery("<div id='treeview-wrapper', class='treeview-ctn'>");
                treeviewWrapper.append("<div id='core-tree'/>");

                treeviewWrapper.css({
                    height: "200px",
                    width: "250px",
                    position:'absolute',
                    top: '200px',
                    left: '400px',
                    border: '1px solid green',
                    backgroundColor: 'white',
                    overflowY: 'scroll'
                });
```

````
jQuery(treeviewWrapper).find("#core-tree").tree({dragAndDrop:true, data: DataExample.example_data, autoOpen: false});

               setTimeout(function () {
                   jQuery('body').append(treeviewWrapper);
               }, 5000);
````

**Comment by mbraak** [comment] 2015-09-30 10:35
I think the problem is that the wrapper element has `position: absolute`.

Perhaps you can wrap the `treeview-wrapper` in another container:

```
<div id="treeview-abs">
  <div id="treeview-wrapper">
    <div id="core-tree" />
  </div>
</div>
```

css:

```css
#treeview-abs {
  height: 200px,
  width: 250px,
  position: absolute,
  top: 200px,
  left: 400px,
}

#treeview-wrapper {
  position: relative;
  overflowY: scroll;
}
```

**Comment by hbaptiste** [comment] 2015-09-30 10:41
it works fine if the structure is already in the DOM.
But if we append the tree after (with setTimeout) it won't scroll.

**Comment by mbraak** [comment] 2015-09-30 11:11
Ok. I will try to reproduce the error.

**Comment by mbraak** [comment] 2015-09-30 11:29
I could reproduce the bug. Thanks for finding it!

I added a fix to the `dev` branch. The new version will initialize the autoscroll only when the user starts dragging a node.

Please let me know if the solution works.

**Comment by hbaptiste** [comment] 2015-09-30 11:30
:+1:  I'll give it a try :)

**Comment by hbaptiste** [comment] 2015-09-30 12:46
It seems to work fine! I using the lazy loading feature, do you think it will play nice with it?
Thanks again for your help.

**Comment by mbraak** [comment] 2015-09-30 12:47
Great! The lazy-loading feature should be no problem.

**Comment by mbraak** [comment] 2015-09-30 12:48
Closing the issue

**Closed by mbraak** 2015-09-30 12:48 UTC

**Comment by hbaptiste** [comment] 2015-09-30 13:27
Is it possible for you to do a tag with this fix? As I'm using jqTtree in my dependencies, I cannot use the dev branch.
Thanks

**Comment by mbraak** [comment] 2015-09-30 13:38
Are you using npm? Because the you can use the commit hook:

```
npm install https://github.com/mbraak/jqTree.git#7db569b4307a32b9bad89968e5fff562f09f6cec
```

**Comment by hbaptiste** [comment] 2015-09-30 13:43
I'm using Bower. It should work too. I think I'll fork your repository.
